name: Build and Test React Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0]
        
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
            node-version: ${{ matrix.node-version }}       
       - name: npm ci, build and test
         # npm ci is similar to npm install but it's probably use env variables CI=true
         run: |
          cd Learning.React/Pokes/Tools
          npm ci 
          npm run build --if-present
          npm test    
